name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# PRごとまたはブランチごとに古いワークフローをキャンセル
concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run type check
      run: npm run typecheck
    
    - name: Run tests
      run: npm test -- --passWithNoTests
    
    - name: Build application
      run: npm run build
    
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    
    - name: Install Playwright
      run: npx playwright install chromium
    
    - name: Run E2E tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        npm run test:e2e
      env:
        CI: true
    
    - name: Run E2E tests (Windows/macOS)
      if: matrix.os != 'ubuntu-latest'
      run: npm run test:e2e
      env:
        CI: true
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report-${{ matrix.os }}
        path: |
          playwright-report/
          test-results/