name: E2E xvfb-run Test

on:
  push:
    branches: [ feat/processing-controls ]

# 同じブランチの古いワークフローをキャンセル
concurrency:
  group: e2e-xvfb-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-xvfb:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libgtk-3-0 \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          libxtst6 \
          libatspi2.0-0 \
          libx11-xcb1 \
          libgbm1
    
    - name: Install Playwright
      run: npx playwright install --with-deps chromium
    
    - name: Run E2E tests with xvfb-run
      run: xvfb-run -a -s "-screen 0 1280x1024x24 -ac -nolisten tcp -dpi 96 +extension GLX" npm run test:e2e
      env:
        CI: true
        NODE_ENV: test
        E2E_TEST_MODE: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-xvfb-results
        path: |
          playwright-report/
          test-results/