name: E2E Debug

on:
  push:
    branches: [ feat/processing-controls ]

jobs:
  e2e-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo apt-get install -y \
          libasound2 \
          libgbm1 \
          libgtk-3-0 \
          libnss3 \
          libxss1 \
          libxtst6
    
    - name: Install Playwright
      run: npx playwright install chromium
    
    - name: Debug environment
      run: |
        echo "DISPLAY: $DISPLAY"
        echo "Platform: ${{ runner.os }}"
        which xvfb-run || echo "xvfb-run not found"
    
    - name: Run E2E tests with debug
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 &
        sleep 3
        npm run test:e2e
      env:
        CI: true
        DEBUG: pw:browser*,pw:protocol
        PWDEBUG: 1
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-debug-artifacts
        path: |
          playwright-report/
          test-results/