name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run TypeScript check
      run: npm run typecheck
    
    - name: Run unit tests
      run: npm test
    
    - name: Run integration tests
      run: npm run test:integration
    
    - name: Test build
      run: npm run build
    
    - name: Install Playwright
      run: npx playwright install --with-deps
    
    - name: Run E2E tests (smoke tests only)
      run: npm run test:e2e -- --grep "@smoke"
      env:
        CI: true
    
    - name: Comment PR
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const result = '${{ job.status }}';
          const emoji = result === 'success' ? '✅' : '❌';
          const message = result === 'success' 
            ? 'All quality checks passed!' 
            : 'Quality checks failed. Please review the logs.';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${emoji} **PR Quality Check Result**: ${message}`
          });