name: Prepare Release PR

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release'
        required: false
        default: 'auto'
        type: choice
        options:
          - 'auto'
          - 'patch'
          - 'minor'
          - 'major'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release PR (Auto)
        uses: googleapis/release-please-action@v4
        id: release
        if: github.event.inputs.release_type == 'auto' || github.event.inputs.release_type == ''
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-github-release: true
      
      - name: Create Release PR (Explicit)
        uses: googleapis/release-please-action@v4
        id: release-explicit
        if: github.event.inputs.release_type != 'auto' && github.event.inputs.release_type != ''
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          release-as: ${{ github.event.inputs.release_type }}
          skip-github-release: true