name: Process Leak Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: process-check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-process-leak:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libasound2t64 libgbm1 libgtk-3-0 libnss3 libxss1 libxtst6
    
    - name: Install Playwright
      run: npx playwright install --with-deps chromium
    
    - name: Check processes before tests
      run: |
        echo "=== Processes before E2E tests ==="
        ps aux | grep -E "(electron|chromium|node)" | grep -v grep || echo "No relevant processes found"
        echo "=== Process count ==="
        ps aux | grep -E "(electron|chromium|node)" | grep -v grep | wc -l || echo "0"
    
    - name: Run E2E tests
      run: xvfb-run -a -s "-screen 0 1280x1024x24 -ac -nolisten tcp -dpi 96 +extension GLX" npm run test:e2e
      env:
        CI: true
        NODE_ENV: test
        E2E_TEST_MODE: true
    
    - name: Wait for process cleanup
      run: sleep 5
    
    - name: Check processes after tests
      run: |
        echo "=== Processes after E2E tests ==="
        ps aux | grep -E "(electron|chromium|node)" | grep -v grep || echo "No relevant processes found"
        echo "=== Process count ==="
        ps aux | grep -E "(electron|chromium|node)" | grep -v grep | wc -l || echo "0"
        
        # Check specifically for electron processes
        echo "=== Checking for leaked Electron processes ==="
        if ps aux | grep -E "electron.*dist-electron" | grep -v grep; then
          echo "⚠️  WARNING: Found potentially leaked Electron processes!"
          exit 1
        else
          echo "✅ No leaked Electron processes found"
        fi