name: Release (Unsigned)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.1.1)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: x64
            build_cmd: dist:mac-x64
          - os: macos-latest
            arch: arm64
            build_cmd: dist:mac-arm64
          - os: windows-latest
            arch: x64
            build_cmd: dist:win
          - os: ubuntu-latest
            arch: x64
            build_cmd: dist:linux
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build application (unsigned)
      run: npm run ${{ matrix.build_cmd }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # コード署名を無効化
        CSC_IDENTITY_AUTO_DISCOVERY: false
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-build
        path: release/
        retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # CHANGELOGの履歴を取得
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate release notes from CHANGELOG
      id: changelog
      run: |
        # CHANGELOGから今回のバージョンの内容を抽出
        VERSION=${GITHUB_REF#refs/tags/v}
        CHANGELOG_CONTENT=$(sed -n "/## \[${VERSION}\]/,/## \[/p" CHANGELOG.md | head -n -1)
        echo "content<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-artifacts/**/*
        draft: false
        prerelease: false
        body: ${{ steps.changelog.outputs.content }}
        generate_release_notes: false  # CHANGELOGを使うのでfalse
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}